### ISSUE TITLE
Flash of unstyled content when the page is refreshed

### ISSUE THREAD

**Issue by jawache** [aijavascript/aijs.rocks#10]
We seem to be inlining the styles, so adding them into the page via style tags like so:

`<style id="gatsby-inlined-css">h1,h2,h3,h4,h5,h6.... </style>`

This means that the CSS isn't cached in the browser and I think that is what is causing the ugly flash of wrong text font when the page loads or is refreshed.

I can see in the build folder we produce a style.css, I think if we include that instead of inlining the styles it will remove the flash of unstyled content and reduce page size as well.

`<style src="/style.css"></style>`

**Comment by jawache** [comment]
Actually @osamajandali after a bit of research I "think" it's that we need to use typography.toString() instead of injectStyles()? 

See... https://github.com/KyleAMathews/typography.js/issues/113

**Comment by osamajandali** [comment]
as me and @jawache talked, I think it's an issue with not putting google font link in the head so on every refresh it has to load it again.
I will add link on react helmet and should be tested again on live.

**Comment by jawache** [comment]
Hey FYI @osamajandali i'm still seeing the FOUC issue :/ also there are a few fonts that are not loading in production!

<img width="786" alt="screenshot 2018-07-31 11 16 41" src="https://user-images.githubusercontent.com/897523/43478746-933def58-94b3-11e8-81fa-1005c36184ce.png">

**Comment by osamajandali** [comment]
I think the build doesn't copy these file, I will take a look

**Comment by jawache** [comment]
Actually, i'm not sure that's the problem any more, I can't see the google font in the head of the page, so i think it's still downloading the google font from the JS.

**Comment by osamajandali** [comment]
the thing is that this is not the google font, this is icons font.. something I made like font awesome thing that I told you about if you could remember.

**Comment by jawache** [comment]
Oh yeah I think the fontello issues might not be the cause of the flash :/ just maybe some separate caching 

I remember you said that you could have it so you add the google fonts directly in the HTML and not have gatsby add them with javascript, I don't think it would flash if the google fonts were added in the head since the font would already be downloaded by the time the rest of the page loads.
