### ISSUE TITLE
Cab we make the font size larger?

### ISSUE THREAD

**Issue by jawache** [aijavascript/aijs.rocks#16]
My eyesight isn't what it used to be and I'm finding the font really hard to read at its current size. A bit larger and it looks and reads much better.

I've set it to 100%/1.666em (before it's set to 75%/1.666em) 

Before ->

![screenshot 2018-07-27 15 56 05](https://user-images.githubusercontent.com/897523/43328414-d427963c-91b5-11e8-9cdc-508ac9a7c523.png)

After ->

![screenshot 2018-07-27 15 55 52](https://user-images.githubusercontent.com/897523/43328442-e2d34fdc-91b5-11e8-8f9c-3f42bbbdc904.png)

**Comment by osamajandali** [comment]
Done, but I need you test it again and get more people opinion about it.
