### ISSUE TITLE
A clearer blockquote or admonition style for highlighting things

### ISSUE THREAD

**Issue by jawache** [aijavascript/aijs.rocks#18]
This is what a blockquote renders as:

```
> **Note**
> 
> The API by default doesn’t return the emotion, you need to explicitly specify the query param `returnFaceAttributes=emotion`
```

<img width="857" alt="screenshot 2018-07-27 15 54 18" src="https://user-images.githubusercontent.com/897523/43328596-531a44ee-91b6-11e8-8c3d-84e8591c5121.png">

I've got similar "admonition" styles on my website, like so:

<img width="864" alt="screenshot 2018-07-27 16 02 38" src="https://user-images.githubusercontent.com/897523/43328671-8d4d68c6-91b6-11e8-954f-2e818a9d1208.png">

**Comment by osamajandali** [comment]
I have made this design, what do you think about it ?
![image](https://user-images.githubusercontent.com/13832392/43370031-8837551a-9380-11e8-97e3-73019b9804cf.png)

**Comment by jawache** [comment]
Perfect 😁
