### ISSUE TITLE
Change anchor color to brand blue

### ISSUE THREAD

**Issue by jawache** [aijavascript/aijs.rocks#20]

**Comment by jawache** [comment]
@osamajandali I think we need a different colour or style for links, the yellow and blue on white is too light, this is what the blue looks like:

<img width="958" alt="screenshot 2018-07-28 16 03 51" src="https://user-images.githubusercontent.com/897523/43357870-f211c800-927f-11e8-9e29-317e8d2ecbcf.png">

**Comment by osamajandali** [comment]
![image](https://user-images.githubusercontent.com/13832392/43370499-83ca7e78-9388-11e8-933b-abbf7fcdca04.png)
how about something like this `#47bbdd`
