### ISSUE TITLE
Submission instructions incorrect

### ISSUE THREAD

**Issue by alex-saunders** [aijavascript/aijs.rocks#45]
Not sure if I'm 100% correct on this but the submission instructions indicate that you should 'create a folder inside `/pages/`', should this not be `/pages/inspire`? as this is where the showcased projects live?

**Comment by EleanorHaproff** [comment]
Yes, you're right - will get that changed. Well spotted!

**Comment by EleanorHaproff** [comment]
Have updated! Thanks for the headsup alex
