### ISSUE TITLE
Layout issues with different length descriptions

### ISSUE THREAD

**Issue by jawache** [aijavascript/aijs.rocks#8]
![screenshot 2018-07-26 16 04 33](https://user-images.githubusercontent.com/897523/43270758-c2d6b75a-90ed-11e8-9538-e627d8798209.png)

<img width="985" alt="screenshot 2018-07-26 16 03 27" src="https://user-images.githubusercontent.com/897523/43270765-c6fc098e-90ed-11e8-8ce3-6eb95916c066.png">

**Comment by osamajandali** [comment]
For the overflow text we should hide the it right ?
