### ISSUE TITLE
Content only scrolls when mouse is over content area

### ISSUE THREAD

**Issue by jawache** [aijavascript/aijs.rocks#9]
Was quite confusing to figure out :/ scrolling only works when on the content area. Can we have the left/right panels static/fixed perhaps instead so scrolling anywhere on the page will scroll the whole page?

![kgxhmiq3or](https://user-images.githubusercontent.com/897523/43271010-54792dfa-90ee-11e8-9960-928b0b4feced.gif)

**Comment by osamajandali** [comment]
Fixed
